---
- name: Configure Pilot room endpoints
  hosts: pilot_endpoints
  become: true
  gather_facts: true
  roles:
    - room_endpoint

- name: Configure Pilot display nodes
  hosts: pilot_display_nodes
  become: true
  gather_facts: true
  roles:
    - display_node
