[env:hot-water]
platform = espressif8266@4.2.1
board = esp8285
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dout
build_flags =
  -D HOT_WATER_FIRMWARE_VERSION=\"0.2.5\"
  -D WIFI_SSID=\"${sysenv.ENERGY_MANAGER_WIFI_SSID}\"
  -D WIFI_PASSWORD=\"${sysenv.ENERGY_MANAGER_WIFI_PASSWORD}\"
  -D API_TOKEN=\"${sysenv.ENERGY_MANAGER_HOT_WATER_API_TOKEN}\"
lib_deps =
  bblanchon/ArduinoJson@^7.4.2
